language: python

python:
  - "3.4"


before_install:
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


install:
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform

  - pip install -r requirements.txt

cache:
  directories:
  - "$HOME/.cache/pip"
  - lib/python3.4/site-packages
  - lib/python3.5/site-packages
  - lib/python3.6/site-packages

script: 
  - nosetests --with-coverage tests --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_ok-client_15ba00a1b2_0
  - python -m properform Push 47.88.50.110:15554 asdf_ok-client_15ba00a1b2_0 ./profile_ok-client_15ba00a1b2_0



 #2017-09-12 11:40:30 modified at 0